#!/bin/python

import math
import os
import random
import re
import sys

def aVeryBigSum(ar):
    add1 = 0
    for i in ar:
        add1 += i
    return add1
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(raw_input())

    ar = map(long, raw_input().rstrip().split())

    result = aVeryBigSum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
