#!/bin/python

import math
import os
import random
import re
import sys

def compareTriplets(a, b):
    a1 = 0
    b1 = 0
    for i in range(len(a)):
        if a[i]>b[i]:
            a1 += 1
        elif a[i]<b[i]:
            b1 += 1
    return a1,b1
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = map(int, raw_input().rstrip().split())

    b = map(int, raw_input().rstrip().split())

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
